// Données mockées temporaires pour le composant Marketing & Promotions
// À utiliser en attendant la création des tables dans Supabase

export const mockBoostingServices = [
  {
    id: '1',
    name: 'Boost Recommandation',
    description: 'Mise en avant sur la page d\'accueil et produits recommandés',
    type: 'recommendation' as const,
    base_price: 5000,
    pricing_model: 'per_page_day' as const,
    is_active: true,
    features: ['Page d\'accueil', 'Produits recommandés', 'Durée 7 jours'],
    status: 'available' as const,
    created_by: 'admin',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '2',
    name: 'Boost Bannière',
    description: 'Bannières publicitaires sur le site',
    type: 'banner' as const,
    base_price: 10000,
    pricing_model: 'per_page_day' as const,
    is_active: true,
    features: ['Bannières visuelles', 'Ciblage par page', 'Durée personnalisable'],
    status: 'available' as const,
    created_by: 'admin',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '3',
    name: 'Boost WhatsApp',
    description: 'Promotion via WhatsApp Business',
    type: 'whatsapp' as const,
    base_price: 15000,
    pricing_model: 'per_message_country' as const,
    is_active: true,
    features: ['Messages ciblés', 'Ciblage géographique', 'Suivi des conversions'],
    status: 'available' as const,
    created_by: 'admin',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  }
]

export const mockBoostingCampaigns = [
  {
    id: '1',
    vendor_id: 'vendor-1',
    service_id: '1',
    type: 'recommendation' as const,
    status: 'active' as const,
    start_date: '2024-01-15',
    end_date: '2024-01-22',
    target_pages: ['home', 'product', 'best_sellers'],
    duration: 7,
    total_cost: 5000,
    payment_status: 'paid' as const,
    payment_id: 'pay-123',
    payment_method: 'feexpay',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    vendor_name: 'Boutique Mode',
    vendor_email: 'contact@boutiquemode.com'
  },
  {
    id: '2',
    vendor_id: 'vendor-2',
    service_id: '2',
    type: 'banner' as const,
    status: 'pending' as const,
    start_date: '2024-01-20',
    end_date: '2024-01-27',
    target_pages: ['home', 'new_arrivals'],
    duration: 7,
    total_cost: 10000,
    payment_status: 'pending' as const,
    created_at: '2024-01-18T14:30:00Z',
    updated_at: '2024-01-18T14:30:00Z',
    vendor_name: 'Tech Store',
    vendor_email: 'info@techstore.com'
  },
  {
    id: '3',
    vendor_id: 'vendor-3',
    service_id: '3',
    type: 'whatsapp' as const,
    status: 'active' as const,
    start_date: '2024-01-10',
    end_date: '2024-01-17',
    target_pages: ['whatsapp'],
    duration: 7,
    total_cost: 15000,
    payment_status: 'paid' as const,
    payment_id: 'pay-456',
    payment_method: 'feexpay',
    created_at: '2024-01-10T09:15:00Z',
    updated_at: '2024-01-10T09:15:00Z',
    vendor_name: 'Électronique Plus',
    vendor_email: 'ventes@electroniqueplus.com'
  }
]

export const mockPromotions = [
  {
    id: '1',
    name: 'Soldes d\'Hiver',
    description: 'Réductions exceptionnelles sur toute la collection hiver',
    type: 'reduction' as const,
    discount_type: 'percentage' as const,
    discount_value: 20,
    min_purchase_amount: 50000,
    max_discount_amount: 10000,
    usage_limit: 100,
    used_count: 45,
    start_date: '2024-01-01',
    end_date: '2024-01-31',
    status: 'active' as const,
    applicable_products: [],
    applicable_categories: ['vetements', 'chaussures'],
    conditions: 'Valable sur les articles en solde uniquement',
    created_at: '2023-12-25T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    vendor_id: 'vendor-1',
    vendor_name: 'Boutique Mode'
  },
  {
    id: '2',
    name: 'Livraison Gratuite',
    description: 'Livraison offerte dès 25000 FCFA d\'achat',
    type: 'reduction' as const,
    discount_type: 'free_shipping' as const,
    discount_value: 0,
    min_purchase_amount: 25000,
    usage_limit: 500,
    used_count: 123,
    start_date: '2024-01-01',
    end_date: '2024-03-31',
    status: 'active' as const,
    applicable_products: [],
    applicable_categories: [],
    conditions: 'Livraison standard uniquement',
    created_at: '2023-12-28T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    vendor_name: 'Admin'
  },
  {
    id: '3',
    name: 'Code Promo TECH15',
    description: '15% de réduction sur tous les produits tech',
    type: 'code' as const,
    discount_type: 'percentage' as const,
    discount_value: 15,
    min_purchase_amount: 30000,
    usage_limit: 50,
    used_count: 12,
    start_date: '2024-01-15',
    end_date: '2024-02-15',
    status: 'active' as const,
    applicable_products: [],
    applicable_categories: ['electronique', 'informatique'],
    conditions: 'Code promo à usage unique par client',
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    vendor_id: 'vendor-2',
    vendor_name: 'Tech Store'
  }
]
